version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Generate database migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
